# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true
#       templates:
#         - condition:
#             contains:
#               docker.container.labels.filebeat.enable: "true"
#           config:
#             - type: filestream
#               id: bankapi-logs-${data.docker.container.id}
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log
#               parsers:
#                 # 1. This unwraps the Docker JSON shell natively
#                 - container:
#                     stream: all
#                     format: auto
#                 # 2. This applies your multiline logic to the raw text inside
#                 - multiline:
#                     type: pattern
#                     pattern: '^\d{4}-\d{2}-\d{2}'
#                     negate: true
#                     match: after

# processors:
#   - add_docker_metadata:
#       host: "unix:///var/run/docker.sock"
#   - add_host_metadata: ~
#   - add_fields:
#       target: app
#       fields:
#         name: bankapi

# output.logstash:
#   hosts: ["graylog:5044"]

# logging.level: info
# logging.to_files: false


###### General Filebeat Configuration v7 ######
# filebeat.inputs:
#   - type: docker
#     containers.ids:
#       - "*"
#     processors:
#       - add_docker_metadata: ~


# output.logstash:
#   hosts: ["graylog-host:5044"]

filebeat.inputs:
- type: filestream
  id: bankapi-logs
  enabled: true
  paths:
    - /logs/*.log

output.logstash:
  hosts: ["graylog:5044"]