# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true
#       templates:
#         - condition:
#             contains:
#               docker.container.labels.filebeat.enable: "true"
#           config:
#             - type: container
#               paths:
#                 - /var/lib/docker/containers/${data.docker.container.id}/*.log
#               json.keys_under_root: true
#               json.overwrite_keys: true
#               json.add_error_key: true
#               multiline:                         
#                 pattern: '^\d{4}-\d{2}-\d{2}'
#                 negate: true
#                 match: after

# processors:
#   - add_docker_metadata:
#       host: "unix:///var/run/docker.sock"
#   - add_host_metadata: ~
#   - add_fields:
#       target: app
#       fields:
#         name: bankapi

# output.logstash:
#   hosts: ["graylog:5044"]

# logging.level: info
# logging.to_files: false


###### General Filebeat Configuration v7 ######
filebeat.inputs:
  - type: docker
    containers.ids:
      - "*"
    processors:
      - add_docker_metadata: ~


output.logstash:
  hosts: ["graylog-host:5044"]